Handle the schema registry url ending with '/'
confluentinc/libserdes pull request #38
Opened 2021-01-12 10:52 UTC by fanfuxiaoran

2021-01-12 20:56 UTC, edenhill requested changes

2021-01-12 20:56 UTC, edenhill commented on src/rest.c
> +                if (url_len > 0 && ul->urls[ul->idx][url_len - 1] == '/')
suggest removing all trailing slashes:
```c
while (url_len > 0 && ..urls[url_len-1] == '/')
   url_len--;   
```

2021-01-12 20:56 UTC, edenhill commented on src/rest.c
> +                snprintf(tmpurl, url_len + 1, "%s", ul->urls[ul->idx]);
I think this can be simplified by passing the string length:
`sprintf(tmpurl, "%.*s%s", (int)url_len, ul->urls[ul->idx], url_path);`

2021-01-12 20:57 UTC, edenhill commented on src/rest.c
> +        size_t url_len;
move this down to the blcok where it is used (the do { block)

2021-01-13 02:16 UTC, fanfuxiaoran commented on src/rest.c
> +                if (url_len > 0 && ul->urls[ul->idx][url_len - 1] == '/')
Good suggestion.

2021-01-13 09:49 UTC, edenhill requested changes

2021-01-13 09:49 UTC, edenhill commented on src/rest.c
> +        size_t url_len;
it should go at the beginning of the `do {` block:
```c
do {
  size_t url_len;
```

2021-01-13 09:49 UTC, edenhill commented on src/rest.c
> +                sprintf(tmpurl, "%.*s%s", url_len, ul->urls[ul->idx], url_path);
need to cast url_len to int

2021-01-13 10:16 UTC, edenhill requested changes

2021-01-13 10:16 UTC, edenhill commented on src/rest.c
> +                /*  Hanld the '/' in url
typo: "Handle"

2021-01-13 10:23 UTC, fanfuxiaoran commented on src/rest.c
> +                /*  Hanld the '/' in url
Thanks a lot!

2021-01-13 10:23 UTC, edenhill commented
[clabot:check]

2021-01-13 10:23 UTC, edenhill approved these changes
LGTM!

2021-01-13 10:24 UTC, merged

2021-01-13 10:24 UTC, edenhill commented
Thank you!